name: credit-default-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.4
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - jupyter=1.0.0
  - jupyterlab=4.0.9
  - notebook=7.0.6
  - pyarrow=14.0.1
  - openpyxl=3.1.2
  - pip=23.3.1
  - pip:
      - xgboost==2.0.3
      - lightgbm==4.1.0
      - catboost==1.2.2
      - imbalanced-learn==0.11.0
      - optuna==3.5.0
